xcodeproj 'ResourceMapperDemo/ResourceMapperDemo.xcodeproj'

target "ResourceMapperDemo" do
    platform :osx, '10.9'
    link_with 'ResourceMapperDemo'
	
	pod "ResourceMapper", :path => "../ResourceMapper.podspec"
end
